### ISSUE TITLE
Не указаны все зависимости для запуска

### ISSUE THREAD

**Issue by sleonia** [razrabs-media/ui-kit#1]
Не хватает зависимостей проекта

```bash
git clone https://github.com/razrabs-media/ui-kit.git
cd ui-kit
yarn
npm run storybook:start
```

<img width="1424" alt="Screenshot 2022-08-21 at 11 54 48" src="https://user-images.githubusercontent.com/46787637/185783543-f1c5d695-e299-4f81-8856-5bbeb05dac6b.png">

<img width="1424" alt="Screenshot 2022-08-21 at 11 56 46" src="https://user-images.githubusercontent.com/46787637/185783585-a8d4f402-818c-48c7-9c4e-3712987eac4e.png">

**Comment by evist0** [comment]
репозиторий только создан, думаю, в течение недели приведу его в порядок)
